In [8]:
from sklearn.feature_extraction.text import CountVectorizer # TF
from sklearn.feature_extraction.text import TfidfVectorizer # TF-iDF
from sklearn.metrics.pairwise import cosine_similarity

In [9]:
corpus = [
    "O estudo de bias algorítmico é importante.",
    "Algoritmos podem conter bias ocultos.",
    "A inteligência artificial aprende com os dados.",
    "Dados ruins geram modelos com bias e erros.",
    "O estudo da ética na inteligência artificial é fundamental."
]

print(f"Corpus carregado com { len(corpus) } documentos")
#

Corpus carregado com 5 documentos

# Stopwords

In [10]:
from nltk.stem.snowball import stopwords
# !pip install -q spacy nltk
import nltk
nltk.download("stopwords")

stopwords_nltk = stopwords.words("portuguese")

[nltk_data] Downloading package stopwords to /home/renata/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

# Bag of Words

In [11]:
vectorizer = CountVectorizer(max_df=0.8,
                             lowercase=True,
                             stop_words=stopwords_nltk)

X_bow = vectorizer.fit_transform(corpus)

print(vectorizer.get_feature_names_out())
print(X_bow.toarray())

['algoritmos' 'algorítmico' 'aprende' 'artificial' 'bias' 'conter' 'dados'
 'erros' 'estudo' 'fundamental' 'geram' 'importante' 'inteligência'
 'modelos' 'ocultos' 'podem' 'ruins' 'ética']
[[0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0]
 [1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 1 1 0 0 1 0 0 1 0 0 1 0]
 [0 0 0 1 0 0 0 0 1 1 0 0 1 0 0 0 0 1]]

In [12]:
import pandas as pd

pd.DataFrame(X_bow.toarray(), columns=vectorizer.get_feature_names_out())

,algoritmos,algorítmico,aprende,artificial,bias,conter,dados,erros,estudo,fundamental,geram,importante,inteligência,modelos,ocultos,podem,ruins,ética
0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0
1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,1,1,0,0
2,0,0,1,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,1,0,1,1,0,0,1,0,0,1,0,0,1,0
4,0,0,0,1,0,0,0,0,1,1,0,0,1,0,0,0,0,1

# TF-iDF

In [13]:
vectorizer = TfidfVectorizer(max_df=0.8,
                             min_df=1,
                             lowercase=True,
                             stop_words=stopwords_nltk)

X_tfidf = vectorizer.fit_transform(corpus)

print(vectorizer.get_feature_names_out())
print(X_tfidf.toarray())

['algoritmos' 'algorítmico' 'aprende' 'artificial' 'bias' 'conter' 'dados'
 'erros' 'estudo' 'fundamental' 'geram' 'importante' 'inteligência'
 'modelos' 'ocultos' 'podem' 'ruins' 'ética']
[[0.         0.56801408 0.         0.         0.38040565 0.
  0.         0.         0.45827018 0.         0.         0.56801408
  0.         0.         0.         0.         0.         0.        ]
 [0.47412465 0.         0.         0.         0.3175268  0.47412465
  0.         0.         0.         0.         0.         0.
  0.         0.         0.47412465 0.47412465 0.         0.        ]
 [0.         0.         0.5819515  0.4695148  0.         0.
  0.4695148  0.         0.         0.         0.         0.
  0.4695148  0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.29656989 0.
  0.35727423 0.4428322  0.         0.         0.4428322  0.
  0.         0.4428322  0.         0.         0.4428322  0.        ]
 [0.         0.         0.         0.40580082 0.         0.
  0.         0.         0.40580082 0.50297966 0.         0.
  0.40580082 0.         0.         0.         0.         0.50297966]]

In [14]:
pd.DataFrame(X_tfidf.toarray(), columns=vectorizer.get_feature_names_out())

,algoritmos,algorítmico,aprende,artificial,bias,conter,dados,erros,estudo,fundamental,geram,importante,inteligência,modelos,ocultos,podem,ruins,ética
0,0.000000,0.568014,0.000000,0.000000,0.380406,0.000000,0.000000,0.000000,0.458270,0.00000,0.000000,0.568014,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
1,0.474125,0.000000,0.000000,0.000000,0.317527,0.474125,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.474125,0.474125,0.000000,0.00000
2,0.000000,0.000000,0.581951,0.469515,0.000000,0.000000,0.469515,0.000000,0.000000,0.00000,0.000000,0.000000,0.469515,0.000000,0.000000,0.000000,0.000000,0.00000
3,0.000000,0.000000,0.000000,0.000000,0.296570,0.000000,0.357274,0.442832,0.000000,0.00000,0.442832,0.000000,0.000000,0.442832,0.000000,0.000000,0.442832,0.00000
4,0.000000,0.000000,0.000000,0.405801,0.000000,0.000000,0.000000,0.000000,0.405801,0.50298,0.000000,0.000000,0.405801,0.000000,0.000000,0.000000,0.000000,0.50298

In [15]:
query = ["Como identificar bias em inteligência artificial?"]

In [16]:
# 1. Transformar a query usando o MESMO vectorizer que a gente usou antes

query_vec = vectorizer.transform(query)

pd.DataFrame(query_vec.toarray(), columns=vectorizer.get_feature_names_out())


# 2. Calcular a similaridade de cosse entre a query e todos os documentos

similaridades = cosine_similarity(query_vec, X_tfidf).flatten()

# 3. Rankear os resultados
resultados = pd.DataFrame({"documento": corpus, "similaridade": similaridades})


# 4. Ordenar os resultados pelos resultados mais próximos
resultados.sort_values(by="similaridade", ascending=False, inplace=True)

resultados

                                           documento  similaridade
2    A inteligência artificial aprende com os dados.      0.572638
4  O estudo da ética na inteligência artificial é...      0.494930
0         O estudo de bias algorítmico é importante.      0.192563
1              Algoritmos podem conter bias ocultos.      0.160733
3        Dados ruins geram modelos com bias e erros.      0.150125