In [1]:
# !pip install gensim nltk pyLDAVis pandas

import pandas as pd

import nltk
from nltk.corpus import stopwords
from gensim.utils import simple_preprocess
from sklearn.datasets import fetch_20newsgroups

nltk.download('stopwords')

stop_words = stopwords.words('english')
stop_words.extend(
    ['from', 'subject', 're', 'edu', 'use', 'organization', 'cc', 'writes']
)


categories = ['sci.space','comp.graphics', 'talk.religion.misc', 'sci.med']
newsgroups = fetch_20newsgroups(subset='all', categories=categories, remove=('headers', 'footers', 'quotes'))

[nltk_data] Downloading package stopwords to /home/renata/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
data = pd.DataFrame({'text': newsgroups.data, 'target': newsgroups.target})
data

                                                   text  target
0     Hi, \n\n\tIs anyone into medical imaging?  I h...       0
1     What is NASA's annual budget?\nThis year will ...       2
2     \n\nNo, just a little anger.  Normally I don't...       1
3     \nAs you note, the research is mixed, so there...       1
4     \nHow does that compare with JPEG on the same ...       0
...                                                 ...     ...
3573  On a slightly different note:\n\nThere are two...       3
3574  \n\n\n\n\nI don't have to "try reading a bit",...       2
3575  \n\n\n\n\n\nWell, I thought it must have been ...       2
3576  \nOnly if he doesn't spend more than a billion...       2
3577                                                  .       3

[3578 rows x 2 columns]

In [3]:
def clean_text(text):
    tokens = simple_preprocess(str(text), deacc=True, min_len=3)
    return [token for token in tokens if token not in stop_words]

data['tokens'] = data['text'].apply(clean_text)

data = data[data['tokens'].map(len) > 0]

In [4]:
data

,text,target,tokens
0,"Hi, \n\n\tIs anyone into medical imaging? I h...",0,"[anyone, medical, imaging, good, ray, tracing,..."
1,What is NASA's annual budget?\nThis year will ...,2,"[nasa, annual, budget, year, years, back, wpul..."
2,"\n\nNo, just a little anger. Normally I don't...",1,"[little, anger, normally, rip, people, lips, e..."
3,"\nAs you note, the research is mixed, so there...",1,"[note, research, mixed, consensus, role, fatty..."
4,\nHow does that compare with JPEG on the same ...,0,"[compare, jpeg, images, hardware, far, size, s..."
...,...,...,...
3572,\nI have a long sighted eye and a short sighte...,1,"[long, sighted, eye, short, sighted, eye, righ..."
3573,On a slightly different note:\n\nThere are two...,3,"[slightly, different, note, two, buildings, st..."
3574,"\n\n\n\n\nI don't have to ""try reading a bit"",...",2,"[try, reading, bit, pat, work, government, con..."
3575,"\n\n\n\n\n\nWell, I thought it must have been ...",2,"[well, thought, must, joke, get, joke, name, r..."
3576,\nOnly if he doesn't spend more than a billion...,2,"[spend, billion, dollars, since, prize, going,..."

In [1]:
import gensim.corpora as corpora
from gensim.models.ldamodel import LdaModel

id_dict = corpora.Dictionary(data['tokens'])


corpus = [id_dict.doc2bow(text) for text in data['tokens']]


lda_model = LdaModel(
    corpus=corpus,
    id2word=id_dict,
    num_topics=4,
    chunksize=100,
    passes=20,
    per_word_topics=True,
    random_state=42
)

for idx, topic in lda_model.print_topics(-1):
    print('Topic: {} \nWords: {}'.format(idx, topic))

NameError: name 'data' is not defined